//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HireMockup
{
    using System;
    using System.Collections.Generic;
    
    public partial class HireAsset
    {
        public int hireID { get; set; }
        public string hireName { get; set; }
        public string hireType { get; set; }
        public Nullable<decimal> dailyRate { get; set; }
    }
}
