//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HireMockup
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Id { get; set; }
        public string customerName { get; set; }
        public string customerSurname { get; set; }
        public string addressLine1 { get; set; }
        public string addressLine2 { get; set; }
        public decimal accountBalance { get; set; }
    }
}
